controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_home_redirect:
    path: /
    controller: 'App\Controller\HomeController::index'

app_home:
    path: /home
    controller: 'App\Controller\HomeController::index'